name:                crik-types
version:             0.1.0.0
github:              "githubuser/crik-types"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/crik-types#readme>

dependencies:
- aeson >= 1.0.0.0
- base >= 4.7 && < 5
- servant >= 0.13
- text >= 1.0.0.0
- template-haskell >= 2.0 && <= 3.0

library:
  exposed-modules: 
  - Crik.API
  - Crik.Types
  - Crik.Types.Video
  - Crik.Types.Video.Id
  - Crik.Types.File
  - Crik.Types.File.Id
  - Crik.Types.Library
  other-modules:
  - Crik.TH.DeriveHttpData
  - Crik.Types.Internal
